### ISSUE TITLE
Other types to support?

### ISSUE THREAD

**Issue by ckaran** [smessmer/binary-layout#13]
Not really an issue, but something to think about for the future of this project.  Do you want to support any of the types in `libcore`?  Or is that out of scope for this project?  I'm thinking about things like the [atomic](https://doc.rust-lang.org/core/sync/atomic/index.html) types, which have simple mappings to other primitive types.  The issue for the atomics in particular is that you need to specify the [access ordering](https://doc.rust-lang.org/core/sync/atomic/enum.Ordering.html), which means that we'd be making statements regarding ordering that end users don't want applied.

Alternatively, you could declare that anything in *any* library as out of scope of the project.  That is probably the simplest, and would let you polish and finish the project.  Updates would only include any new language primitives that are added (e.g., `never`, should it ever stabilize).

**Comment by smessmer** [comment]
I have a first experimental implementation of nesting in the `feature/nesting` branch. That branch also has an example in `tests/nested.rs`.

**Comment by ckaran** [comment]
I like where you're going with it!  I haven't tested it, and given how work looks like for the next few weeks, I probably won't be able to, but I'll try to pull periodically to see how you're doing.  Thank you!

**Comment by smessmer** [comment]
Nested layouts are implemented in https://github.com/smessmer/binary-layout/commit/3b67f467c7d390125376ba5d2430136e47da6232 and will be part of the 3.0 release

**Comment by smessmer** [comment]
The 4.0 release now supports types that can throw errors when reading, e.g. 1-byte booleans.

**Comment by smessmer** [comment]
Thay also implements `TryLayoutAs`, but I actually found a way to combine it i to the `LayoutAs` trait without requiring a separate trait. `LayoutAs` is now always fallible, but if implementors use `std::convert::Infallible` as the error type, then we will still generate the infallible `read`/`write` API for them. 

Remaining unimplemented ideas from this discussion:
- bools as 1 bit
- slices for other types than just u8
Both are mentioned in the project README. I'm closing this issue for now.
