### ISSUE TITLE
Is it possible to have nested layouts?

### ISSUE THREAD

**Issue by dheater** [smessmer/binary-layout#17]
Is it possible to have nested layouts?

For example, I have a multibyte header that I want to define and reuse as a field in other layouts

Something like this:
```
define_layout!(header_t, BigEndian, {
    version: u16,
    length: u16,
};

define_layout!(packet, BigEndian {
    header: header_t,
    field1: u16,
    field2: u16,
    data: [u8],
}
```

**Comment by smessmer** [comment]
not currently, but I'm working on it. You can take a look at the "feature/nesting" branch and the tests/nested.rs file in there if you want a preview.

**Comment by smessmer** [comment]
Nested layouts are implemented in https://github.com/smessmer/binary-layout/commit/3b67f467c7d390125376ba5d2430136e47da6232 and will be part of the 3.0 release
