### ISSUE TITLE
possible to add a NativeEndian marker?

### ISSUE THREAD

**Issue by carlsverre** [smessmer/binary-layout#21]
I am using this crate to work with sqlite datastructures of which most are BigEndian. However there is one structure which always uses the current machines native endianness. I would love to use this crate to handle all of my data wrangling however it appears there is no way to disable the explicit endianness conversions? From a cursory glance it looks very possible - what do you think? I can probably take a crack at this if you're ok with it and there are no crazy unknowns.

Thanks!

**Comment by smessmer** [comment]
Hi, thanks for reaching out. I'm open to adding native endian as long as users have to clearly mark it and it doesn't happen implicitly. I can review the PR if you want to create one.

**Comment by carlsverre** [comment]
Sounds good! Will take a crack at it. Thanks!
