### ISSUE TITLE
Feature request: provide "size up to array" for open ended layouts ending with arrays

### ISSUE THREAD

**Issue by rdaum** [smessmer/binary-layout#23]
Nice crate. Small feature request...

Consider the following:

```rust
define_layout!(page_node_leaf, LittleEndian, {
    header: page_node_header_common::NestedView,
    num_pairs: u64,
    start_value_offset: u32,
    key_data: [u8],
});
```

SIZE is inherently unknowable because of the `[u8]`, so is None, understandable.  But `binary_layout` does in fact know the size of everything before the array. It would be nice to have an additional value representing the non-dynamic sized portion of the layout.

Right now the workaround I've come to is to break things up into nested layouts, with the dynamic layout added to a nested fixed-size layout. This works, but it gets awkward when you start to get more than a couple levels deep with nesting. Having a size which represented the knowable portion of the layout (not sure what to call the constant) would be much handier.

**Comment by smessmer** [comment]
You should be able to use `key_data::OFFSET` for this.

**Comment by rdaum** [comment]
Aha, sorry, I never saw that. Makes sense, thanks.
