### ISSUE TITLE
Ability to retrieve the non-variable SIZE of the struct

### ISSUE THREAD

**Issue by vlovich** [smessmer/binary-layout#26]
I find myself regularly wanting to get the non-variable portion of structs that have a trailing `[u8]` field. Would it be useful to add a `SIZE_FOR_FIXED_FIELDS` generated member that's `usize` instead of `Option<usize>`?

For a motivating example, I may have structs like this:

```
binary_layout!(generic_header, LittleEndian, {
   version: u8,
   rest: [u8],
});

binary_layout!(header_v1, LittleEndian, {
 ....
})

binary_layout!(header_v2, LittleEndian, {
 ....
})

let mut serialized = [0u8; generic_header::SIZE_FOR_FIXED_FIELDS + header_v1::SIZE_FOR_FIXED_FIELDS.max(header_v2::SIZE_FOR_FIXED_FIELDS)];
```

Of course, some kind of tagged field support based on contents would be nice but that's a separate issue.

EDIT: reset --> rest

**Comment by smessmer** [comment]
Would `generic_header::reset::OFFSET` work for you?

**Comment by vlovich** [comment]
Oh neat. Didn't know about that. Yes, it kind of does although not as clean in terms of being self-documenting when reading the code as a constant hanging off the overall struct. Requires a bit of non-local knowledge that that is indeed the variable length field which needs to be documented (+ when code evolves things may shift around & make the comment stale)

**Comment by vlovich** [comment]
@smessmer does you closing the issue mean you're not willing to add a `NON_VARIABLE_SIZE` parameter on the top-level struct (or whatever name makes sense)?

**Comment by smessmer** [comment]
I think the current approach using a field offset is more general and we don't need to add a separate parameter.
