### ISSUE TITLE
Supporting `unit` and `never`.

### ISSUE THREAD

**Issue by ckaran** [smessmer/binary-layout#9]
Both `unit` ([`()`](https://doc.rust-lang.org/std/primitive.unit.html)) and `never` ([`!`](https://doc.rust-lang.org/std/primitive.never.html)) are zero-sized types, so there isn't any true binary representation for them.  That said, they *are* primitive types, and `define_layout!()` could in theory encounter one (or both) of them.  In addition, the documentation for `never` says that we should implement non-panicing traits for it whenever possible. Would it make sense to implement all the various traits for them except `LayoutAs`?  My thought is that they accept and produce slices of zero length, which shouldn't cause any issues.

**Comment by ckaran** [comment]
OK, I created the code for this, but realized that I have no idea how to deal with never.  The issue is that I want to make the implementation's existence contingent on someone activating the never feature via `#![feature(never_type)]`.  Unfortunately, using `cfg` the way I *thought* it would work, doesn't actually work.  Any ideas?

**Comment by smessmer** [comment]
Which traits concretely are you thinking about implementing for `never`?
